export const LOADING="LOADING";
export const GETDATA="GETDATA";
export const ADDTOCART="ADDTOCART";
export const CARTITEMINCREMENT="CARTITEMINCREMENT";
export const CARTITEMDECREMENT="CARTITEMDECREMENT";

